# Generated by Django 5.0.2 on 2024-10-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('address', models.CharField()),
                ('contact_phone', models.CharField()),
                ('rooms', models.JSONField()),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
